export const actionTypes = {
  SET_START_TIME: "SET_START_TIME",
  SET_END_TIME: "SET_END_TIME",
  SET_PRICE_MAX: "SET_PRICE_MAX",
  SET_LOCATION: "SET_LOCATION",
  SET_PRICE_MIN: "SET_PRICE_MIN",
  SET_TAG_NAME: "SET_TAG_NAME",
};
